{{- range $service := .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $service.name }}
spec:
  defaultBackend:
    service:
      name: {{ $service.name }}
      port:
        number: 8080
---
{{- end}}