{{- range $service := .Values.services}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
spec:
  selector:
    app: {{ $service.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
{{- end}}