apiVersion: v1
kind: Pod
metadata:
  name: authentication
  labels:
    app.kubernetes.io/name: authentication
spec:
  containers:
    - name: authentication
      image: null116/auth-service:latest
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app.kubernetes.io/name: authentication
  ports:
    - protocol: TCP
      port: 16000
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-authentication-ingress
spec:
  defaultBackend:
    service:
      name: authentication-service
      port:
        number: 16000